apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: concourse-web
  labels:
    app: course
    concourse: web
spec:
  strategy:
    type: Recreate
  replicas: 1
  revisionHistoryLimit: 20
  template:
    metadata:
      labels:
        app: concourse
        concourse: web
    spec:
      restartPolicy: Always
      containers:
      - image: concourse/concourse:3.3.4
        name: concourse
        args: [ web ]
        env:
        - name: postgres_username
          valueFrom:
            secretKeyRef:
              name: concourse
              key: postgres_user
        - name: postgres_password
          valueFrom:
            secretKeyRef:
              name: concourse
              key: postgres_password
        - name: CONCOURSE_BASIC_AUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: concourse
              key: concourse_auth_username
        - name: CONCOURSE_BASIC_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: concourse
              key: concourse_auth_password
        - name: CONCOURSE_EXTERNAL_URL
          value: "http://concourse-web.default.svc.cluster.local:8080"
        - name: CONCOURSE_POSTGRES_DATA_SOURCE
          value: postgres://$(postgres_username):$(postgres_password)@concourse-postgres.default.svc.cluster.local:5432/concourse?sslmode=disable
        volumeMounts:
        - name: concourse-keys
          mountPath: /concourse-keys
          readOnly: true
      volumes:
      - name: concourse-keys
        secret:
          secretName: concourse
          defaultMode: 0400
---
apiVersion: v1
kind: Service
metadata:
  name: concourse-web
  labels:
    concourse: web
    app: concourse
spec:
  ports:
  - name: web
    port: 8080
  - name: tsa
    port: 2222
  selector:
    app: concourse
    concourse: web
---
apiVersion: v1
kind: Service
metadata:
  name: concourse-web-extern
  labels:
    concourse: web
    app: concourse
spec:
  type: NodePort
  ports:
  - name: web
    port: 8080
  selector:
    app: concourse
    concourse: web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: concourse-worker
  labels:
    app: course
    concourse: worker
spec:
  strategy:
    type: Recreate
  replicas: 3
  revisionHistoryLimit: 20
  template:
    metadata:
      labels:
        app: concourse
        concourse: worker
    spec:
      restartPolicy: Always
      containers:
      - image: concourse/concourse:3.3.4
        name: concourse
        args: [ worker ]
        env:
        - name: CONCOURSE_TSA_HOST
          value: concourse-web.default.svc.cluster.local
        volumeMounts:
        - name: concourse-keys
          mountPath: /concourse-keys
          readOnly: true
        securityContext:
          privileged: true
      volumes:
      - name: concourse-keys
        secret:
          secretName: concourse-workers
          defaultMode: 0400