apiVersion: v1
kind: Secret
metadata:
  name: concourse
stringData:
  concourse_auth_username: < your data >
  concourse_auth_password: < your data >
  postgres_user: < your data >
  postgres_password: < your data >
  session_signing_key: < your data >
  tsa_host_key: < your data >
  authorized_worker_keys: < your data >
---
apiVersion: v1
kind: Secret
metadata:
  name: concourse-workers
stringData:
  tsa_host_key.pub: < your data >
  worker_key: < your data >